# Arewa Data Science Academy

## Deep Learning Cohort

### Name: Bernard Buckman

#### Title: Week 1 Solution

#### Exercise Solution

1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on torch.Tensor.
* The documentation on torch.cuda.

2. Create a random tensor with shape (7, 7)

In [15]:
# Import torch
import torch

# Create random number
random_tensor1 = torch.rand(size=(7, 7))
random_tensor1

tensor([[0.2866, 0.6969, 0.6094, 0.9159, 0.2113, 0.6026, 0.2451],
        [0.5987, 0.6389, 0.4717, 0.7172, 0.8488, 0.3116, 0.4492],
        [0.7666, 0.9559, 0.6096, 0.9445, 0.8096, 0.9320, 0.3337],
        [0.1386, 0.2095, 0.5133, 0.0942, 0.5921, 0.6533, 0.4434],
        [0.0360, 0.3801, 0.0184, 0.9007, 0.9712, 0.9944, 0.1582],
        [0.0088, 0.3903, 0.2252, 0.1161, 0.2298, 0.6769, 0.3364],
        [0.1955, 0.5684, 0.3501, 0.3967, 0.8923, 0.3389, 0.3232]])

3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [18]:
# Create another random tensor
random_tensor2 = torch.rand(size=(1, 7))

# Perform matrix multiplication
print(f'Shape of tensor A -> {random_tensor1.shape}')
print(f'Shape of tensor B -> {random_tensor2.shape}')
ans = torch.matmul(random_tensor1, random_tensor2.T)
print(f'Shape of new tensor -> {ans.shape}')
ans

Shape of tensor A -> torch.Size([7, 7])
Shape of tensor B -> torch.Size([1, 7])
Shape of new tensor -> torch.Size([7, 1])


tensor([[1.9936],
        [2.4545],
        [3.1403],
        [1.7749],
        [2.1245],
        [1.1724],
        [1.9287]])

4. Set the random seed to 0 and do 2 & 3 over again.

The output should be:

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

In [20]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
rand1 = torch.rand(size=(7,7))
rand2 = torch.rand(size=(1, 7))

# Matrix multiply tensors
result = torch.mm(rand1, rand2.T)
result


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

* If there is, set the GPU random seed to 1234.

In [25]:
# Set random seed on the GPU
torch.cuda.seed()

# Count number of devices
# torch.cuda.device_count()

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [27]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
rand1 = torch.rand(size=(2,3))
rand2 = torch.rand(size=(2,3))

# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"

rand1_to_gpu = rand1.to(device)
rand2_to_gpu = rand2.to(device)
print(rand1_to_gpu)
print(rand2_to_gpu)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))

In [28]:
# Perform matmul on tensor_A and tensor_B
answer = torch.mm(rand1_to_gpu, rand2_to_gpu.T)
answer

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
print(f'Maximum value is {answer.max()}')

# Find min
print(f'Minimum value is {answer.min()}')

Maximum value is 0.5617256760597229
Minimum value is 0.3647301495075226


9. Find the maximum and minimum index values of the output of 7.

In [30]:
# Find arg max
print(f'Index where the max value occurs is {answer.argmax()}')

# Find arg min
print(f'Index where the min value occurs is {answer.argmin()}')

Index where the max value occurs is 3
Index where the min value occurs is 0


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
        

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
